import { getAgentM365Tools } from "../lib/m365ToolRegistry.js";

export type AgentSummary = {
  id: string;
  name: string;
  title: string;
  tier: "Board" | "Executive" | "Governor" | "Specialist" | "Subagent";
  reportsTo?: string;
  summary: string;
  toolsAllowed?: string[];
  toolsForbidden?: string[];
  m365Tools?: string[];
  escalationTargets?: string[];
};

function withM365(id: string, base: Omit<AgentSummary, "m365Tools">): AgentSummary {
  return { ...base, m365Tools: getAgentM365Tools(id) };
}

export const agentRegistry: AgentSummary[] = [
  withM365("chairman", {
    id: "chairman",
    name: "Chairman",
    title: "Chairman of the Board",
    tier: "Board",
    summary: "Final human authority for approvals and constitutional changes.",
    toolsAllowed: ["Read-only dashboards", "Approval/deny UI"],
    toolsForbidden: ["Direct execution tools"],
    escalationTargets: [],
  }),
  withM365("atlas", {
    id: "atlas",
    name: "Atlas",
    title: "President · Sole Execution Layer",
    tier: "Executive",
    reportsTo: "chairman",
    summary: "Executes actions only after gates approve; writes audit trail for everything. Full M365 admin.",
    toolsAllowed: ["Internal job runner", "Email dispatch", "Audit writer", "Ledger writer", "M365 admin"],
    toolsForbidden: ["Unlogged external actions", "Policy tampering"],
    escalationTargets: ["chairman"],
  }),
  withM365("binky", {
    id: "binky",
    name: "Binky",
    title: "Chief Research Officer",
    tier: "Executive",
    reportsTo: "atlas",
    summary: "Runs daily intel cycles and produces cited briefs for executive decisions.",
    toolsAllowed: ["Docs drafting", "Email", "Read-only dashboards", "Web research"],
    toolsForbidden: ["DB writes", "Ledger writes", "Deployments"],
    escalationTargets: ["atlas", "chairman"],
  }),
  withM365("tina", {
    id: "tina",
    name: "Tina",
    title: "Treasurer · Financial Controls",
    tier: "Governor",
    reportsTo: "atlas",
    summary: "Financial oversight, ledger discipline, and spend reporting.",
    toolsAllowed: ["Ledger writer", "Accounting reports", "Email"],
    toolsForbidden: ["Deployments", "Policy edits"],
    escalationTargets: ["atlas", "chairman"],
  }),
  withM365("larry", {
    id: "larry",
    name: "Larry",
    title: "Corporate Secretary · Audit & Forensics",
    tier: "Governor",
    reportsTo: "atlas",
    summary: "Compliance + policy governance; ensures audit integrity and constitutional adherence.",
    toolsAllowed: ["Policy reader", "Docs", "Email"],
    toolsForbidden: ["DB writes", "Ledger writes", "Deployments", "Policy edits"],
    escalationTargets: ["atlas", "chairman"],
  }),
  withM365("jenny", {
    id: "jenny",
    name: "Jenny",
    title: "General Counsel · Corporate Law",
    tier: "Specialist",
    reportsTo: "atlas",
    summary: "Holds corporate structure documentation and reviews governance/legal packets.",
    toolsAllowed: ["Docs reading", "Policy editor (proposal)"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["atlas"],
  }),
  withM365("benny", {
    id: "benny",
    name: "Benny",
    title: "IP Counsel · Copyright/Trademark",
    tier: "Specialist",
    reportsTo: "atlas",
    summary: "Prevents IP infringement; reviews content/product monetization for rights conflicts.",
    toolsAllowed: ["Docs reading", "IP register editor (proposal)"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["atlas"],
  }),
  withM365("cheryl", {
    id: "cheryl",
    name: "Cheryl",
    title: "Customer Support Specialist",
    tier: "Executive",
    reportsTo: "binky",
    summary: "Support intake, triage, escalation routing, and customer feedback intelligence with strict traceability.",
    toolsAllowed: ["Email inbox (support@)", "Ticket system", "Documentation/KB", "Escalation router"],
    toolsForbidden: ["Database/ledger access", "Deployments", "Policy edits"],
    escalationTargets: ["binky", "tina", "larry", "jenny", "atlas"],
  }),
  withM365("daily-intel", {
    id: "daily-intel",
    name: "Daily-Intel",
    title: "Intel Aggregator · Daily Briefing",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Aggregates incoming research and drafts the structured daily intelligence packet for Binky.",
    toolsAllowed: ["Web research", "Docs reading", "Email drafting"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("archy", {
    id: "archy",
    name: "Archy",
    title: "Research Subagent · Operations",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Collects operational intel and summarizes actionable implementation options.",
    toolsAllowed: ["Web research", "Docs reading"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("venny", {
    id: "venny",
    name: "Venny",
    title: "Research Subagent · Vendors & Tools",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Tracks vendors, tools, pricing, and integration opportunities; produces comparisons.",
    toolsAllowed: ["Web research", "Docs reading", "Spreadsheet drafting"],
    toolsForbidden: ["Purchases", "Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("penny", {
    id: "penny",
    name: "Penny",
    title: "Research Subagent · Policy Watch",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Monitors compliance, privacy, and platform policy shifts that impact SGL and agent behavior.",
    toolsAllowed: ["Web research", "Docs reading"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("donna", {
    id: "donna",
    name: "Donna",
    title: "Content & Copy Subagent",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Produces copy, descriptions, and structured content based on Binky's cited research.",
    toolsAllowed: ["Docs drafting"],
    toolsForbidden: ["Publishing"],
    escalationTargets: ["binky"],
  }),
  withM365("cornwall", {
    id: "cornwall",
    name: "Cornwall",
    title: "Accounting & Ledger Subagent",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Keeps pricing, margins, job costs, and ledger entries clean and reconcilable.",
    toolsAllowed: ["Ledger viewer", "Spreadsheet drafting"],
    toolsForbidden: ["Transfers", "Execution tools"],
    escalationTargets: ["atlas"],
  }),
  withM365("link", {
    id: "link",
    name: "Link",
    title: "Integrations Subagent",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Maps APIs, webhooks, and integration wiring; drafts implementation steps and test plans.",
    toolsAllowed: ["Docs reading", "Code drafting"],
    toolsForbidden: ["Deploying to prod"],
    escalationTargets: ["atlas"],
  }),
  withM365("dwight", {
    id: "dwight",
    name: "Dwight",
    title: "Platform Reliability Subagent · DevOps",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Focuses on deployments, uptime, observability, and environment drift prevention.",
    toolsAllowed: ["Logs viewing", "Runbook drafting"],
    toolsForbidden: ["Unapproved production changes"],
    escalationTargets: ["atlas"],
  }),
  withM365("reynolds", {
    id: "reynolds",
    name: "Reynolds",
    title: "Security & Threat Subagent",
    tier: "Subagent",
    reportsTo: "larry",
    summary: "Flags security risks, secrets exposure, auth weaknesses, and recommends mitigations.",
    toolsAllowed: ["Static analysis", "Docs reading"],
    toolsForbidden: ["Offensive actions"],
    escalationTargets: ["larry"],
  }),
  withM365("emma", {
    id: "emma",
    name: "Emma",
    title: "Executive Assistant Subagent",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Turns decisions into task lists, follow-ups, and clean communications across the org.",
    toolsAllowed: ["Docs drafting", "Email drafting"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["atlas"],
  }),
  withM365("fran", {
    id: "fran",
    name: "Fran",
    title: "Design & UX Subagent",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Supports UI clarity: layouts, content hierarchy, and consistent visual language.",
    toolsAllowed: ["Design notes", "Code drafting (UI)"],
    toolsForbidden: ["Direct deploys"],
    escalationTargets: ["atlas"],
  }),
  withM365("kelly", {
    id: "kelly",
    name: "Kelly",
    title: "People Ops Subagent",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Keeps roles, responsibilities, onboarding, and internal clarity clean and explicit.",
    toolsAllowed: ["Docs drafting"],
    toolsForbidden: ["Legal determinations"],
    escalationTargets: ["atlas"],
  }),
  withM365("terry", {
    id: "terry",
    name: "Terry",
    title: "QA & Verification Subagent",
    tier: "Subagent",
    reportsTo: "larry",
    summary: "Validates outputs: correctness, reproducibility, and that nothing violates policy or truth layer.",
    toolsAllowed: ["Test checklist editor", "Docs reading"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["larry"],
  }),
  withM365("timmy", {
    id: "timmy",
    name: "Timmy",
    title: "Build & Automation Subagent",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Helps wire automations and internal routines; drafts code changes and scripts safely.",
    toolsAllowed: ["Code drafting", "Docs reading"],
    toolsForbidden: ["Destructive execution"],
    escalationTargets: ["atlas"],
  }),
  withM365("sunday", {
    id: "sunday",
    name: "Sunday",
    title: "Comms & Publishing Coordinator",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Coordinates publishing schedules and channel packaging once Atlas approves.",
    toolsAllowed: ["Docs drafting"],
    toolsForbidden: ["Publishing"],
    escalationTargets: ["binky"],
  }),
  withM365("mercer", {
    id: "mercer",
    name: "Mercer",
    title: "Customer Acquisition Strategist",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Designs outreach strategies, pipeline analysis, and acquisition playbooks.",
    toolsAllowed: ["Email drafting", "Docs reading", "Web research"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["atlas"],
  }),
  // ── New agents ──────────────────────────────────────────────────────────────
  withM365("petra", {
    id: "petra",
    name: "Petra",
    title: "Project Manager · Cross-Agent Coordination",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Manages tasks, sprints, and deliverables across agents using Microsoft Planner.",
    toolsAllowed: ["Planner write", "Docs drafting", "Teams draft"],
    toolsForbidden: ["Execution tools", "Ledger writes"],
    escalationTargets: ["atlas"],
  }),
  withM365("porter", {
    id: "porter",
    name: "Porter",
    title: "SharePoint Portal Manager",
    tier: "Subagent",
    reportsTo: "larry",
    summary: "Owns SharePoint intranet structure, document library taxonomy, and site publishing.",
    toolsAllowed: ["SharePoint read", "Docs drafting"],
    toolsForbidden: ["SharePoint destructive operations without approval"],
    escalationTargets: ["larry", "atlas"],
  }),
  withM365("claire", {
    id: "claire",
    name: "Claire",
    title: "Calendar & Scheduling Coordinator",
    tier: "Subagent",
    reportsTo: "emma",
    summary: "Manages Atlas's calendar, schedules meetings, prepares agendas, coordinates Teams invites.",
    toolsAllowed: ["Calendar read", "Email drafting", "Meeting draft"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["emma", "atlas"],
  }),
  withM365("victor", {
    id: "victor",
    name: "Victor",
    title: "Video Production Specialist",
    tier: "Subagent",
    reportsTo: "donna",
    summary: "Manages Clipchamp video production pipeline: source media → edit → export → OneDrive.",
    toolsAllowed: ["Clipchamp write", "OneDrive write"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["donna", "atlas"],
  }),
  withM365("frank", {
    id: "frank",
    name: "Frank",
    title: "Forms & Data Collection Agent",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Designs Microsoft Forms for intake, surveys, onboarding, and feedback. Routes data to agents.",
    toolsAllowed: ["Forms read", "Excel read", "Docs reading"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("sandy", {
    id: "sandy",
    name: "Sandy",
    title: "Bookings & Appointments Agent",
    tier: "Subagent",
    reportsTo: "emma",
    summary: "Manages Microsoft Bookings for client-facing appointments, demos, and consultations.",
    toolsAllowed: ["Bookings read", "Calendar read", "Email drafting"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["emma", "mercer", "atlas"],
  }),
];
