import { getAgentM365Tools } from "../lib/m365ToolRegistry.js";

export type AgentSummary = {
  id: string;
  name: string;
  title: string;
  tier: "Board" | "Executive" | "Governor" | "Specialist" | "Subagent";
  reportsTo?: string;
  summary: string;
  toolsAllowed?: string[];
  toolsForbidden?: string[];
  m365Tools?: string[];
  escalationTargets?: string[];
};

function withM365(id: string, base: Omit<AgentSummary, "m365Tools">): AgentSummary {
  return { ...base, m365Tools: getAgentM365Tools(id) };
}

export const agentRegistry: AgentSummary[] = [
  withM365("chairman", {
    id: "chairman",
    name: "Chairman",
    title: "Chairman of the Board",
    tier: "Board",
    summary: "Final human authority for approvals and constitutional changes.",
    toolsAllowed: ["Read-only dashboards", "Approval/deny UI"],
    toolsForbidden: ["Direct execution tools"],
    escalationTargets: [],
  }),
  withM365("atlas", {
    id: "atlas",
    name: "Atlas",
    title: "President · Sole Execution Layer",
    tier: "Executive",
    reportsTo: "chairman",
    summary: "Executes actions only after gates approve; writes audit trail for everything. Full M365 admin.",
    toolsAllowed: ["Internal job runner", "Email dispatch", "Audit writer", "Ledger writer", "M365 admin"],
    toolsForbidden: ["Unlogged external actions", "Policy tampering"],
    escalationTargets: ["chairman"],
  }),
  withM365("binky", {
    id: "binky",
    name: "Binky",
    title: "Chief Research Officer",
    tier: "Executive",
    reportsTo: "atlas",
    summary: "Runs daily intel cycles and produces cited briefs for executive decisions.",
    toolsAllowed: ["Docs drafting", "Email", "Read-only dashboards", "Web research"],
    toolsForbidden: ["DB writes", "Ledger writes", "Deployments"],
    escalationTargets: ["atlas", "chairman"],
  }),
  withM365("tina", {
    id: "tina",
    name: "Tina",
    title: "Chief Financial Officer · CFO",
    tier: "Governor",
    reportsTo: "atlas",
    summary: "Owns Atlas UX financial strategy, cash flow, budget controls, and CFO-level reporting.",
    toolsAllowed: ["Ledger writer", "Accounting reports", "Email", "Budget rules editor", "Spend alerts"],
    toolsForbidden: ["Deployments", "Policy edits"],
    escalationTargets: ["atlas", "chairman"],
  }),
  withM365("larry", {
    id: "larry",
    name: "Larry",
    title: "Corporate Secretary · Audit & Forensics",
    tier: "Governor",
    reportsTo: "atlas",
    summary: "Compliance + policy governance; ensures audit integrity and constitutional adherence.",
    toolsAllowed: ["Policy reader", "Docs", "Email"],
    toolsForbidden: ["DB writes", "Ledger writes", "Deployments", "Policy edits"],
    escalationTargets: ["atlas", "chairman"],
  }),
  withM365("jenny", {
    id: "jenny",
    name: "Jenny",
    title: "General Counsel · Corporate Law",
    tier: "Specialist",
    reportsTo: "atlas",
    summary: "Holds corporate structure documentation and reviews governance/legal packets.",
    toolsAllowed: ["Docs reading", "Policy editor (proposal)"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["atlas"],
  }),
  withM365("benny", {
    id: "benny",
    name: "Benny",
    title: "IP Counsel · Copyright/Trademark",
    tier: "Specialist",
    reportsTo: "atlas",
    summary: "Prevents IP infringement; reviews content/product monetization for rights conflicts.",
    toolsAllowed: ["Docs reading", "IP register editor (proposal)"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["atlas"],
  }),
  withM365("cheryl", {
    id: "cheryl",
    name: "Cheryl",
    title: "Customer Support Specialist",
    tier: "Executive",
    reportsTo: "binky",
    summary: "Support intake, triage, escalation routing, and customer feedback intelligence with strict traceability.",
    toolsAllowed: ["Email inbox (support@)", "Ticket system", "Documentation/KB", "Escalation router"],
    toolsForbidden: ["Database/ledger access", "Deployments", "Policy edits"],
    escalationTargets: ["binky", "tina", "larry", "jenny", "atlas"],
  }),
  withM365("daily-intel", {
    id: "daily-intel",
    name: "Daily-Intel",
    title: "Intel Aggregator · Daily Briefing",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Aggregates incoming research and drafts the structured daily intelligence packet for Binky.",
    toolsAllowed: ["Web research", "Docs reading", "Email drafting"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("archy", {
    id: "archy",
    name: "Archy",
    title: "Research Subagent · Binky Intel Team",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Deep-dive research specialist for Binky — runs targeted investigations on competitors, industry, and platform activity; returns cited summaries.",
    toolsAllowed: ["Web research", "Docs reading", "Spreadsheet drafting"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("venny", {
    id: "venny",
    name: "Venny",
    title: "Image Production Specialist · Visual Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Produces branded image assets, graphics, and visual media for all social channels — from source files to ready-to-publish output via OneDrive.",
    toolsAllowed: ["Video editor", "OneDrive write", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("penny", {
    id: "penny",
    name: "Penny",
    title: "Facebook Ads & Multi-Platform Scheduler",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Plans Facebook ad campaigns and coordinates AI-generated content distribution across all connected social platforms.",
    toolsAllowed: ["Facebook Ads API", "Meta Business Suite", "Content scheduler"],
    toolsForbidden: ["Spending without Atlas approval", "Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("donna", {
    id: "donna",
    name: "Donna",
    title: "Reddit Community Manager · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages Atlas UX Reddit presence — monitors communities, drafts engagement replies, and queues all posts for human approval.",
    toolsAllowed: ["Reddit API", "Docs drafting"],
    toolsForbidden: ["Direct publishing without approval gate"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("cornwall", {
    id: "cornwall",
    name: "Cornwall",
    title: "Pinterest Publishing Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages the Atlas UX Pinterest presence — publishes pins, curates boards, and drives discovery traffic.",
    toolsAllowed: ["Pinterest API", "Image assets", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("link", {
    id: "link",
    name: "Link",
    title: "LinkedIn Publishing Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages the Atlas UX LinkedIn channel — GPT-generated copy, scheduled posts, and audience growth.",
    toolsAllowed: ["LinkedIn API", "Docs drafting", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("dwight", {
    id: "dwight",
    name: "Dwight",
    title: "Threads Publishing Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages the Atlas UX Threads channel — drafts and publishes short-form conversational content.",
    toolsAllowed: ["Threads API", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("reynolds", {
    id: "reynolds",
    name: "Reynolds",
    title: "Blog Content & Publishing Agent",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Writes and publishes Atlas UX blog content — converts YouTube transcripts to SEO posts and cross-posts excerpts to LinkedIn and X.",
    toolsAllowed: ["Blog CMS", "Docs drafting", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("emma", {
    id: "emma",
    name: "Emma",
    title: "Alignable Business Networking Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages Atlas UX presence on Alignable — posts business content, connects with prospects, and surfaces networking intel for Mercer.",
    toolsAllowed: ["Alignable API", "Docs drafting", "Email drafting"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("fran", {
    id: "fran",
    name: "Fran",
    title: "Facebook Page & Groups Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages Atlas UX Facebook Page and Groups — publishes posts, monitors comments, and runs community engagement.",
    toolsAllowed: ["Facebook Graph API", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("kelly", {
    id: "kelly",
    name: "Kelly",
    title: "X (Twitter) Publishing Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages the Atlas UX X channel — schedules posts, auto-DMs new followers, and tracks brand engagement.",
    toolsAllowed: ["X (Twitter) API", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("terry", {
    id: "terry",
    name: "Terry",
    title: "Tumblr Publishing Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Manages the Atlas UX Tumblr blog — formats and publishes content for Tumblr's creative community.",
    toolsAllowed: ["Tumblr API", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("timmy", {
    id: "timmy",
    name: "Timmy",
    title: "TikTok Content Agent · Social Media",
    tier: "Subagent",
    reportsTo: "sunday",
    summary: "Produces and publishes short-form video content for TikTok — trend-aligned hooks, captions, and video briefs.",
    toolsAllowed: ["TikTok API", "Video assets", "Content scheduler"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["sunday", "atlas"],
  }),
  withM365("sunday", {
    id: "sunday",
    name: "Sunday",
    title: "Comms & Technical Document Writer",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Drafts technical documents, internal memos, and comms briefs from Binky's research output — routes all finished docs to Atlas for approval.",
    toolsAllowed: ["Docs drafting"],
    toolsForbidden: ["Publishing"],
    escalationTargets: ["binky"],
  }),
  withM365("mercer", {
    id: "mercer",
    name: "Mercer",
    title: "Customer Acquisition Strategist",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Designs outreach strategies, pipeline analysis, and acquisition playbooks.",
    toolsAllowed: ["Email drafting", "Docs reading", "Web research"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["atlas"],
  }),
  // ── New agents ──────────────────────────────────────────────────────────────
  withM365("petra", {
    id: "petra",
    name: "Petra",
    title: "Project Manager · Cross-Agent Coordination",
    tier: "Subagent",
    reportsTo: "atlas",
    summary: "Manages tasks, sprints, and deliverables across agents using Microsoft Planner.",
    toolsAllowed: ["Planner write", "Docs drafting", "Teams draft"],
    toolsForbidden: ["Execution tools", "Ledger writes"],
    escalationTargets: ["atlas"],
  }),
  withM365("porter", {
    id: "porter",
    name: "Porter",
    title: "SharePoint Portal Manager",
    tier: "Subagent",
    reportsTo: "larry",
    summary: "Owns SharePoint intranet structure, document library taxonomy, and site publishing.",
    toolsAllowed: ["SharePoint read", "Docs drafting"],
    toolsForbidden: ["SharePoint destructive operations without approval"],
    escalationTargets: ["larry", "atlas"],
  }),
  withM365("claire", {
    id: "claire",
    name: "Claire",
    title: "Calendar & Scheduling Coordinator",
    tier: "Subagent",
    reportsTo: "emma",
    summary: "Manages Atlas's calendar, schedules meetings, prepares agendas, coordinates Teams invites.",
    toolsAllowed: ["Calendar read", "Email drafting", "Meeting draft"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["emma", "atlas"],
  }),
  withM365("victor", {
    id: "victor",
    name: "Victor",
    title: "Video Production Specialist",
    tier: "Subagent",
    reportsTo: "venny",
    summary: "Manages Clipchamp video production pipeline: source media → edit → export → OneDrive.",
    toolsAllowed: ["Clipchamp write", "OneDrive write"],
    toolsForbidden: ["Publishing without Atlas approval"],
    escalationTargets: ["venny", "atlas"],
  }),
  withM365("frank", {
    id: "frank",
    name: "Frank",
    title: "Forms & Data Collection Agent",
    tier: "Subagent",
    reportsTo: "binky",
    summary: "Designs Microsoft Forms for intake, surveys, onboarding, and feedback. Routes data to agents.",
    toolsAllowed: ["Forms read", "Excel read", "Docs reading"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["binky"],
  }),
  withM365("sandy", {
    id: "sandy",
    name: "Sandy",
    title: "Bookings & Appointments Agent",
    tier: "Subagent",
    reportsTo: "emma",
    summary: "Manages Microsoft Bookings for client-facing appointments, demos, and consultations.",
    toolsAllowed: ["Bookings read", "Calendar read", "Email drafting"],
    toolsForbidden: ["Execution tools"],
    escalationTargets: ["emma", "mercer", "atlas"],
  }),
];
