/**
 * Atlas UX Workflow Library — n8n Adapter Manifests
 *
 * Every workflow here is an Atlas UX workflow first.
 * The n8n JSON is the execution engine under the hood — the user never sees "n8n".
 *
 * ID convention:
 *   WF-001–019  Reserved — Atlas core (support, escalation)
 *   WF-020–029  Atlas system / bootstrap
 *   WF-030–039  Research & content creation
 *   WF-040–059  Social media publishing & engagement
 *   WF-060–069  Analytics & competitive intelligence
 *   WF-070–079  Legal, compliance & finance (agent-owned)
 *   WF-080–089  Operations — DevOps, HR, healthcare, education
 *   WF-090–099  Customer service automation
 */

export type AtlasWorkflowDef = {
  id: string;           // WF-### — the Atlas UX canonical ID
  name: string;         // Clean, professional Atlas UX name
  description: string;  // One-line purpose
  category: string;     // Domain label shown in UI
  ownerAgent: string;   // Which Atlas agent owns/executes this
  trigger: string;      // How it starts: webhook | cron | email | manual | telegram
  humanInLoop: boolean; // Does it pause for human approval?
  file: string;         // Path to the n8n JSON (repo-relative)
};

export const n8nWorkflows: AtlasWorkflowDef[] = [

  // ── Orchestration ─────────────────────────────────────────────────────────
  {
    id: "WF-022",
    name: "Atlas Full Orchestrator",
    description: "Master email-driven orchestration pipeline — reads inbox, routes tasks, dispatches agents.",
    category: "orchestration",
    ownerAgent: "atlas",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/ATLAS_orchestrator_FULL_email_endpoint.json",
  },

  // ── Research & Content ────────────────────────────────────────────────────
  {
    id: "WF-030",
    name: "YouTube Transcript → Blog Post",
    description: "Pulls a YouTube video transcript and drafts a formatted blog post for Reynolds to publish.",
    category: "content_creation",
    ownerAgent: "reynolds",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/content_creation/youtube2blog.json",
  },
  {
    id: "WF-031",
    name: "Binky Daily Research Digest",
    description: "Aggregates world news, trends, and hashtags into Binky's daily structured JSON summary.",
    category: "research",
    ownerAgent: "binky",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/research/Binky-Research.json",
  },
  {
    id: "WF-032",
    name: "Sunday Doc Intake & Draft Reply",
    description: "Reads inbound docs, drafts a reply, and gates on Atlas approval before sending.",
    category: "research",
    ownerAgent: "sunday",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/research/SUNDAY_workflow.json.json",
  },
  {
    id: "WF-033",
    name: "Daily-Intel Morning Brief Aggregator",
    description: "Polls world news, industry signals, and social trends; structures and delivers a daily intelligence packet to Binky by 07:00 UTC.",
    category: "research",
    ownerAgent: "daily-intel",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/research/daily_intel_morning_brief.json",
  },
  {
    id: "WF-034",
    name: "Archy Research Deep-Dive",
    description: "Receives a research brief from Binky, runs a multi-source analysis across web, academic, and industry data, and returns a cited summary report.",
    category: "research",
    ownerAgent: "archy",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/research/archy_research_deep_dive.json",
  },

  // ── Social Media ──────────────────────────────────────────────────────────
  {
    id: "WF-040",
    name: "Multi-Platform Social Content Creator",
    description: "AI-generated content published across all connected social platforms in one run.",
    category: "social_media",
    ownerAgent: "penny",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/✨🤖Automate Multi-Platform Social Media Content Creation with AI.json",
  },
  {
    id: "WF-041",
    name: "Blog → LinkedIn & X Auto-Post",
    description: "Watches for new blog posts and automatically publishes excerpts to LinkedIn and X.",
    category: "social_media",
    ownerAgent: "reynolds",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/social_media/auto_blogpost_linkedin_twitter.json",
  },
  {
    id: "WF-042",
    name: "Auto-DM New X Followers",
    description: "Sends a personalized welcome DM to every new X (Twitter) follower.",
    category: "social_media",
    ownerAgent: "kelly",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/social_media/auto_dm_twitter_new_follower.json",
  },
  {
    id: "WF-043",
    name: "Article → X, LinkedIn, Reddit & Threads Publisher",
    description: "Repurposes web articles into platform-optimized posts via Gemini AI.",
    category: "social_media",
    ownerAgent: "atlas",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/Auto-Publish Web Articles as Social Posts for X, LinkedIn, Reddit & Threads with Gemini AI.json",
  },
  {
    id: "WF-044",
    name: "Instagram Comment Response & DM Tracker",
    description: "Monitors Instagram comments, sends DM replies, and logs activity to Google Sheets.",
    category: "social_media",
    ownerAgent: "archy",
    trigger: "manual",
    humanInLoop: false,
    file: "workflows/n8n/social_media/Automated Instagram comment response with DMs & Google Sheets tracking.json",
  },
  {
    id: "WF-045",
    name: "LinkedIn Scheduled Post Creator",
    description: "Generates GPT-4 copy and DALL-E images for scheduled LinkedIn posts.",
    category: "social_media",
    ownerAgent: "link",
    trigger: "cron",
    humanInLoop: true,
    file: "workflows/n8n/social_media/Automated LinkedIn content creation with GPT-4 and DALL-E for scheduled posts.json",
  },
  {
    id: "WF-046",
    name: "Bulk Video → Social Publish (AI Copy + Approval)",
    description: "Processes video assets, generates AI copy, routes for client approval, then publishes.",
    category: "social_media",
    ownerAgent: "venny",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/Bulk Auto-Publish Videos to Social Networks with AI Copy and Client Approval.json",
  },
  {
    id: "WF-047",
    name: "Image & Video Multi-Platform Publisher",
    description: "Distributes image and video assets across X, Instagram, Facebook, and more.",
    category: "social_media",
    ownerAgent: "penny",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/multipass.json",
  },
  {
    id: "WF-048",
    name: "Pinterest Asset Publisher",
    description: "Webhook-triggered pipeline that publishes images and boards to Pinterest.",
    category: "social_media",
    ownerAgent: "cornwall",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/social_media/pinterest.json",
  },
  {
    id: "WF-049",
    name: "Tumblr Post Publisher",
    description: "Posts formatted content to the Atlas Tumblr blog with tracking reference ID.",
    category: "social_media",
    ownerAgent: "terry",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/social_media/tumblr_publish.json",
  },
  {
    id: "WF-050",
    name: "Universal Social Content Generator",
    description: "Telegram-triggered AI content generator that outputs to any configured social platform.",
    category: "social_media",
    ownerAgent: "atlas",
    trigger: "telegram",
    humanInLoop: false,
    file: "workflows/n8n/social_media/Universal Social Media Content Generator with AI.json",
  },

  // ── Reddit / Donna ────────────────────────────────────────────────────────
  {
    id: "WF-051",
    name: "Donna Reddit Subreddit Monitor",
    description: "Polls r/atlas_ux_dev and r/atlasux for new posts and comments, surfaces activity for Donna.",
    category: "social_media",
    ownerAgent: "donna",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/social_media/donna_reddit_owned_monitor.json",
  },
  {
    id: "WF-052",
    name: "Donna Reddit Engagement Scanner",
    description: "Scans r/AiForSmallBusiness, r/AskProgramming, r/ChatGPTCoding and similar for relevant threads. AI drafts a reply and queues it for human approval before posting.",
    category: "social_media",
    ownerAgent: "donna",
    trigger: "cron",
    humanInLoop: true,
    file: "workflows/n8n/social_media/donna_reddit_engage.json",
  },
  {
    id: "WF-053",
    name: "Donna Reddit Reply Approval Gate",
    description: "Human-in-the-loop gate for all Donna Reddit replies. Approved replies are posted immediately; rejected replies are discarded.",
    category: "social_media",
    ownerAgent: "donna",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/donna_reddit_approve.json",
  },
  {
    id: "WF-054",
    name: "Timmy TikTok Content Publisher",
    description: "Generates trend-aligned TikTok hooks and captions from Atlas UX content; routes for human approval then publishes via TikTok API.",
    category: "social_media",
    ownerAgent: "timmy",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/timmy_tiktok_publisher.json",
  },
  {
    id: "WF-055",
    name: "Dwight Threads Post Publisher",
    description: "Converts approved Atlas UX content into Threads-optimized conversational posts and publishes to the Atlas UX Threads account.",
    category: "social_media",
    ownerAgent: "dwight",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/dwight_threads_publisher.json",
  },
  {
    id: "WF-056",
    name: "Emma Alignable Business Updater",
    description: "Posts local business updates to the Atlas UX Alignable profile, surfaces networking prospects, and routes opportunities to Mercer.",
    category: "social_media",
    ownerAgent: "emma",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/emma_alignable_publisher.json",
  },
  {
    id: "WF-057",
    name: "Fran Facebook Page Publisher",
    description: "Publishes posts and Stories to the Atlas UX Facebook Page; surfaces comment threads for response approval and tracks page analytics.",
    category: "social_media",
    ownerAgent: "fran",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/fran_facebook_publisher.json",
  },
  {
    id: "WF-058",
    name: "Sunday Technical Brief & Comms Writer",
    description: "Reads Binky's intel output and drafts structured technical briefs, internal memos, and comms documents; routes to Atlas for approval before distribution.",
    category: "social_media",
    ownerAgent: "sunday",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/social_media/sunday_technical_brief_writer.json",
  },
  {
    id: "WF-059",
    name: "Venny Image Asset Production Pipeline",
    description: "Stages source images in OneDrive, applies branding overlays and production specs, and packages finished visual assets for social channel publishing.",
    category: "social_media",
    ownerAgent: "venny",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/venny_image_production.json",
  },

  // ── Analytics & Intelligence ───────────────────────────────────────────────
  {
    id: "WF-060",
    name: "Competitor Price Intelligence",
    description: "Scrapes competitor pricing pages and delivers a structured delta report to Binky.",
    category: "analytics",
    ownerAgent: "binky",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/analytics/competitor_price_scrapper.json",
  },
  {
    id: "WF-061",
    name: "Ad Campaign Performance Alert",
    description: "Monitors ad performance thresholds and alerts Atlas when KPIs fall out of range.",
    category: "analytics",
    ownerAgent: "atlas",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/media/ad_campain_alert.json",
  },
  {
    id: "WF-062",
    name: "TV Rating Trend Report",
    description: "Aggregates TV rating data and surfaces trend analysis for media strategy decisions.",
    category: "analytics",
    ownerAgent: "binky",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/media/tv_rating_trents.json",
  },
  {
    id: "WF-063",
    name: "Mercer Acquisition Intelligence Report",
    description: "Weekly competitive acquisition scan — surfaces prospect signals from LinkedIn, ProductHunt, and forums; delivers a ranked lead list to Mercer.",
    category: "analytics",
    ownerAgent: "mercer",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/analytics/mercer_acquisition_intel.json",
  },

  // ── Legal, Compliance & Finance ───────────────────────────────────────────
  {
    id: "WF-070",
    name: "Benny IP Triage & Evidence Pack",
    description: "Routes inbound IP claims to Benny, packages evidence, and gates on legal review.",
    category: "legal",
    ownerAgent: "benny",
    trigger: "webhook",
    humanInLoop: true,
    file: "workflows/n8n/legal/triageevidencepack.json",
  },
  {
    id: "WF-071",
    name: "Jenny CLO Intake & Legal Advisory",
    description: "Receives legal intake emails, drafts CLO advisory responses, and gates on Jenny approval.",
    category: "legal",
    ownerAgent: "jenny",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/legal/JENNY-CLO-intake.json",
  },
  {
    id: "WF-072",
    name: "Larry Audit Intake & Compliance Gate",
    description: "Processes audit intake emails, runs a compliance stop, and routes findings to Larry.",
    category: "finance",
    ownerAgent: "larry",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/financial/LARRY-workflow.json",
  },
  {
    id: "WF-073",
    name: "Tina Finance Intake & Risk Gate",
    description: "Reads finance intake emails, evaluates risk tier, and issues CFO advisory reply.",
    category: "finance",
    ownerAgent: "tina",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/financial/TINA-workflow.json.json",
  },

  // ── Operations ────────────────────────────────────────────────────────────
  {
    id: "WF-080",
    name: "GitHub Commit → Jenkins Build Trigger",
    description: "Listens for GitHub push events and triggers the corresponding Jenkins pipeline.",
    category: "devops",
    ownerAgent: "atlas",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/devops/github_jenkins.json",
  },
  {
    id: "WF-081",
    name: "Appointment Confirmation Notifier",
    description: "Sends WhatsApp confirmation messages for scheduled healthcare appointments.",
    category: "operations",
    ownerAgent: "atlas",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/healthcare/appointment_notification.json",
  },
  {
    id: "WF-082",
    name: "Job Application Parser & Router",
    description: "Parses inbound job applications, extracts structured data, and routes to hiring manager.",
    category: "hr",
    ownerAgent: "atlas",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/hr/job_application_parser.json",
  },
  {
    id: "WF-083",
    name: "Quiz Auto-Grader",
    description: "Automatically grades quiz submissions and returns scored results with feedback.",
    category: "education",
    ownerAgent: "atlas",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/education/quiz_auto_grader.json",
  },
  {
    id: "WF-084",
    name: "Petra Sprint Planning & Task Assignment",
    description: "Creates Planner sprint tasks, assigns agents by specialty, tracks blockers in real time, and delivers a sprint status report to Atlas.",
    category: "operations",
    ownerAgent: "petra",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/operations/petra_sprint_planner.json",
  },
  {
    id: "WF-085",
    name: "Sandy Appointment Confirmation & CRM Sync",
    description: "Handles Bookings events — sends confirmation emails, syncs appointment data to the CRM pipeline, and notifies Mercer of new demo prospects.",
    category: "operations",
    ownerAgent: "sandy",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/operations/sandy_appointment_tracker.json",
  },
  {
    id: "WF-086",
    name: "Frank Form Response Aggregator & Router",
    description: "Collects Microsoft Forms submissions, validates and structures response data, and routes it to the correct downstream agent (Cornwall, Cheryl, Mercer).",
    category: "operations",
    ownerAgent: "frank",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/operations/frank_form_aggregator.json",
  },
  {
    id: "WF-087",
    name: "Porter SharePoint Intranet Updater",
    description: "Syncs latest KB content, agent reports, and Petra's project status to the Atlas UX SharePoint intranet pages and document libraries.",
    category: "operations",
    ownerAgent: "porter",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/operations/porter_sharepoint_updater.json",
  },
  {
    id: "WF-088",
    name: "Claire Calendar Prep & Agenda Builder",
    description: "Reads upcoming calendar events, drafts structured meeting agendas in OneNote, and prepares Teams meeting invites for Atlas approval.",
    category: "operations",
    ownerAgent: "claire",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/operations/claire_calendar_prep.json",
  },
  {
    id: "WF-089",
    name: "Victor Video Production Pipeline",
    description: "Stages source video in OneDrive, generates a Clipchamp edit brief for Venny review, exports the finished video asset, and delivers to Sunday for publishing.",
    category: "operations",
    ownerAgent: "victor",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/operations/victor_video_pipeline.json",
  },

  // ── Customer Service Automation ───────────────────────────────────────────
  {
    id: "WF-090",
    name: "Atlas Approval Poller",
    description: "Polls for pending DecisionMemo approvals and nudges the human-in-loop controller.",
    category: "customer_service",
    ownerAgent: "atlas",
    trigger: "cron",
    humanInLoop: true,
    file: "workflows/n8n/customer_service/AtlasUX_Approval_Poller_FIXED.json",
  },
  {
    id: "WF-091",
    name: "Atlas Suggestion Generator",
    description: "Generates proactive task and content suggestions based on business context.",
    category: "customer_service",
    ownerAgent: "atlas",
    trigger: "webhook",
    humanInLoop: false,
    file: "workflows/n8n/customer_service/AtlasUX_Suggestion_Generator_FIXED.json",
  },
  {
    id: "WF-092",
    name: "Cheryl Support Intake & Triage Gate",
    description: "Reads inbound support emails, classifies by severity (billing/bug/compliance/general), drafts a response, and routes to the correct agent before Atlas sends.",
    category: "customer_service",
    ownerAgent: "cheryl",
    trigger: "email",
    humanInLoop: true,
    file: "workflows/n8n/customer_service/cheryl_support_triage.json",
  },

  // ── Platform Intelligence (sub-agents report what's hot on their platform) ──
  {
    id: "WF-093",
    name: "Kelly — X (Twitter) Hot Topics Report",
    description: "Kelly visits X, grabs trending hashtags, viral formats, and hot takes, then reports back to Atlas and the DAILY-INTEL hub.",
    category: "platform_intel",
    ownerAgent: "kelly",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/kelly_x_intel.json",
  },
  {
    id: "WF-094",
    name: "Fran — Facebook Hot Topics Report",
    description: "Fran scans Facebook Pages and Groups for trending topics and viral content, then reports back.",
    category: "platform_intel",
    ownerAgent: "fran",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/fran_facebook_intel.json",
  },
  {
    id: "WF-095",
    name: "Dwight — Threads Trending Report",
    description: "Dwight scans Threads for hot takes, trending conversations, and viral post formats, then reports back.",
    category: "platform_intel",
    ownerAgent: "dwight",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/dwight_threads_intel.json",
  },
  {
    id: "WF-096",
    name: "Timmy — TikTok Trending Sounds & Topics Report",
    description: "Timmy checks TikTok for trending sounds, hashtags, and viral video formats, then reports back.",
    category: "platform_intel",
    ownerAgent: "timmy",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/timmy_tiktok_intel.json",
  },
  {
    id: "WF-097",
    name: "Terry — Tumblr Trending Tags & Posts Report",
    description: "Terry checks Tumblr for trending tags, viral post formats, and hot creative topics, then reports back.",
    category: "platform_intel",
    ownerAgent: "terry",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/terry_tumblr_intel.json",
  },
  {
    id: "WF-098",
    name: "Cornwall — Pinterest Trending Pins & Boards Report",
    description: "Cornwall checks Pinterest for trending pins, board themes, and high-performing visual formats, then reports back.",
    category: "platform_intel",
    ownerAgent: "cornwall",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/cornwall_pinterest_intel.json",
  },
  {
    id: "WF-099",
    name: "Link — LinkedIn Hot Topics & Professional Trends Report",
    description: "Link checks LinkedIn for trending professional topics, viral post formats, and B2B hot takes, then reports back.",
    category: "platform_intel",
    ownerAgent: "link",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/link_linkedin_intel.json",
  },
  {
    id: "WF-100",
    name: "Emma — Alignable Local Business Hot Topics Report",
    description: "Emma checks Alignable for trending local business discussions, hot community topics, and networking opportunities, then reports back.",
    category: "platform_intel",
    ownerAgent: "emma",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/emma_alignable_intel.json",
  },
  {
    id: "WF-101",
    name: "Donna — Reddit Hot Threads & Subreddit Intel Report",
    description: "Donna scans target subreddits for hot threads, trending discussions, and brand-relevant conversations, then reports back.",
    category: "platform_intel",
    ownerAgent: "donna",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/donna_reddit_intel.json",
  },
  {
    id: "WF-102",
    name: "Reynolds — Blog SEO Hot Topics & Trending Searches Report",
    description: "Reynolds researches trending blog topics, SEO opportunities, and top-performing content formats for Atlas UX, then reports back.",
    category: "platform_intel",
    ownerAgent: "reynolds",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/reynolds_blog_intel.json",
  },
  {
    id: "WF-103",
    name: "Penny — Facebook Ads Trending Topics & Ad Intel Report",
    description: "Penny checks Facebook Ads library and trends for top-performing ad formats and messaging angles, then reports back.",
    category: "platform_intel",
    ownerAgent: "penny",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/penny_facebook_ads_intel.json",
  },
  {
    id: "WF-104",
    name: "Archy — Instagram & Visual Trends Report",
    description: "Archy checks Instagram Reels, trending hashtags, and top-performing visual formats for Binky's intel, then reports back.",
    category: "platform_intel",
    ownerAgent: "archy",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/archy_instagram_intel.json",
  },
  {
    id: "WF-105",
    name: "Venny — YouTube & Visual Media Trending Topics Report",
    description: "Venny checks YouTube for trending video topics, thumbnail styles, and high-performing visual formats, then reports back.",
    category: "platform_intel",
    ownerAgent: "venny",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/platform_intel/venny_youtube_intel.json",
  },

  // ── Atlas Aggregation & Task Assignment ───────────────────────────────────
  {
    id: "WF-106",
    name: "Atlas Daily Aggregation & Agent Task Assignment",
    description: "Atlas reads all platform intel reports from the DAILY-INTEL hub, synthesizes a unified intelligence packet, and assigns specific tasks and workflows to every agent for the day.",
    category: "orchestration",
    ownerAgent: "atlas",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/orchestration/atlas_daily_aggregation.json",
  },

  // ── Tool Discovery & Proposal ─────────────────────────────────────────────
  {
    id: "WF-107",
    name: "Atlas Tool Discovery & Proposal",
    description: "Atlas audits every agent's current toolset, identifies gaps and high-value additions, generates a numbered proposal list, and emails Billy for approve/deny. Approved tools are added to KB and wired into the agent's SKILL.md.",
    category: "orchestration",
    ownerAgent: "atlas",
    trigger: "cron",
    humanInLoop: true,
    file: "workflows/n8n/orchestration/atlas_tool_discovery.json",
  },

  // ── YouTube — Venny Video Scraper & Publisher ──────────────────────────────
  {
    id: "WF-110",
    name: "Venny YouTube Video Scraper & KB Ingest",
    description: "Searches YouTube by keyword or monitors specific channels, pulls metadata + transcripts, and stores everything in the KB for team retrieval.",
    category: "content_creation",
    ownerAgent: "venny",
    trigger: "cron",
    humanInLoop: false,
    file: "workflows/n8n/content_creation/venny_youtube_scraper.json",
  },
  {
    id: "WF-111",
    name: "Venny YouTube Shorts Auto-Publisher",
    description: "Takes Victor's exported Clipchamp video from OneDrive and uploads directly to YouTube via Data API v3 with full audit trail.",
    category: "social_media",
    ownerAgent: "venny",
    trigger: "manual",
    humanInLoop: true,
    file: "workflows/n8n/social_media/venny_youtube_upload.json",
  },
];

export default n8nWorkflows;
