export const agentEmails = {
  ATLAS: "atlas@deadappcorp.org",
  BINKY: "binky@deadappcorp.org",
  ARCHY: "archy@deadappcorp.org",
  VENNY: "venny@deadappcorp.org",
  PENNY: "penny@deadappcorp.org",
  CORNWALL: "cornwall@deadappcorp.org",
  DAILY_INTEL: "daily-intel@deadappcorp.org",
  DONNA: "donna@deadappcorp.org",
  DWIGHT: "dwight@deadappcorp.org",
  EMMA: "emma@deadappcorp.org",
  FRAN: "fran@deadappcorp.org",
  KELLY: "kelly@deadappcorp.org",
  LINK: "link@deadappcorp.org",
  REYNOLDS: "reynolds@deadappcorp.org",
  SUNDAY: "sunday@deadappcorp.org",
  TERRY: "terry@deadappcorp.org",
  TIMMY: "timmy@deadappcorp.org",
  JENNY: "jenny@deadappcorp.org",
  BENNY: "benny@deadappcorp.org",
  LARRY: "larry@deadappcorp.org",
  TINA: "tina@deadappcorp.org",
  CHERYL: "cheryl@deadappcorp.org",
  POSTMASTER: "postmaster@deadappcorp.org",
  ABUSE: "abuse@deadappcorp.org",
} as const;

export type AgentEmailKey = keyof typeof agentEmails;
