/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wxeomtjipoirzetjngco"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZW9tdGppcG9pcnpldGpuZ2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNjkwMTEsImV4cCI6MjA4NTY0NTAxMX0._ZJvIZ88G1m8cRyM75VoSYCwSXf5QHtoSQqgTcpUkqg"